# Generated by Django 2.2.5 on 2019-10-23 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('productbacklog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backtrack.ProductBacklog')),
            ],
            bases=('backtrack.productbacklog',),
        ),
        migrations.CreateModel(
            name='ProductBacklogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pointEstimate', models.IntegerField()),
                ('productBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.ProductBacklog')),
            ],
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('estimatedEffortHours', models.TimeField()),
                ('actualEffortHours', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('sprintBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.SprintBacklog')),
            ],
        ),
    ]
