# Generated by Django 2.2.6 on 2019-10-28 09:11

import backtrack.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBacklogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pointEstimate', models.IntegerField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('COMPLETE', 'complete'), ('NOT_YET_STARTED', 'not yet started')], default=backtrack.models.PBIStatus('not yet started'), max_length=50)),
                ('productBacklogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.ProductBacklog')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CURRENT', 'current'), ('COMPLETE', 'complete')], default=backtrack.models.ProjectStatus('current'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DEVELOPER', 'developer'), ('SCRUM_MASTER', 'scrum master'), ('PRODUCT_OWNER', 'product owner')], max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('estimatedEffortHours', models.TimeField()),
                ('actualEffortHours', models.TimeField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('COMPLETE', 'complete'), ('NOT_YET_STARTED', 'not yet started')], default=backtrack.models.TaskStatus('not yet started'), max_length=50)),
                ('pbi', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backtrack.ProductBacklogItem')),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CURRENT', 'current'), ('COMPLETE', 'complete')], default=backtrack.models.SprintStatus('current'), max_length=200)),
                ('productBacklogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.ProductBacklog')),
            ],
        ),
        migrations.AddField(
            model_name='productbacklogitem',
            name='sprintBacklogID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backtrack.SprintBacklog'),
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.Project'),
        ),
    ]
