# Generated by Django 2.2.6 on 2019-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actualEffortHours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimatedEffortHours',
            field=models.FloatField(),
        ),
    ]
