# Generated by Django 2.2.5 on 2019-10-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Not yet started', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='pbi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backtrack.ProductBacklogItem'),
        ),
    ]
