# Generated by Django 2.1.7 on 2019-11-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0002_auto_20191028_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbacklogitem',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'VERY_HIGH'), (2, 'HIGH'), (3, 'NORMAL'), (4, 'LOW'), (5, 'VERY_LOW')], default=3),
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='pointEstimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='sprintBacklogID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backtrack.SprintBacklog'),
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='status',
            field=models.CharField(choices=[('in progress', 'IN_PROGRESS'), ('complete', 'COMPLETE'), ('not yet started', 'NOT_YET_STARTED')], default='not yet started', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('current', 'CURRENT'), ('complete', 'COMPLETE')], default='current', max_length=200),
        ),
        migrations.AlterField(
            model_name='sprintbacklog',
            name='status',
            field=models.CharField(choices=[('current', 'CURRENT'), ('complete', 'COMPLETE')], default='current', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='actualEffortHours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pbi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.ProductBacklogItem'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'IN_PROGRESS'), ('complete', 'COMPLETE'), ('not yet started', 'NOT_YET_STARTED')], default='not yet started', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('developer', 'DEVELOPER'), ('scrum master', 'SCRUM_MASTER'), ('product owner', 'PRODUCT_OWNER')], max_length=200),
        ),
    ]
