# Generated by Django 2.2.5 on 2019-10-25 02:19

import backtrack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0003_auto_20191024_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('current', 'CURRENT'), ('complete', 'COMPLETE')], default=backtrack.models.ProjectStatus('current'), max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'IN_PROGRESS'), ('complete', 'COMPLETE'), ('not yet started', 'NOT_YET_STARTED')], default=backtrack.models.TaskStatus('not yet started'), max_length=50),
        ),
    ]
